server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mhsy?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    type: com.alibaba.druid.pool.DruidDataSource
  #邮箱
  mail:
    host: smtp.163.com #发送邮件服务器
    username: XXXX #发送邮件的邮箱地址
    password: XXXX #客户端授权码，不是邮箱密码,网易的是自己设置的
    properties.mail.smtp.port: 994 #465或者994
    from: XXXX # 发送邮件的地址，和上面username一致 可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
mybatis:
  #  mapper文件
  mapper-locations: classpath:mapper/*.xml
  #  实体类
  type-aliases-package: com.mh.mhsy.mapper