server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    data-username: root
    data-password: root
    url: jdbc:mysql://localhost:3306/mhsy?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  #  mapper文件
  mapper-locations: mapper/*/*Mapper.xml
  #  实体类
  type-aliases-package: com.mh.mhsy.mapper