server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mhsy?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  #  mapper文件
  mapper-locations: classpath:mapper/*.xml
  #  实体类
  type-aliases-package: com.mh.mhsy.mapper